/// Flutter icons MyIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData foodhotdog = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hamburger = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hotdog = IconData(0xf80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
